https://towardsdatascience.com/all-about-feature-scaling-bcc0ad75cb35

https://www.analyticsvidhya.com/blog/2021/08/python-tutorial-working-with-csv-file-for-data-science/

https://machinelearningmastery.com/standardscaler-and-minmaxscaler-transforms-in-python/

## Min-Max scaler

In [108]:

import csv
with open('Data chart template - Template.csv', newline='') as csvfile:
  rows = []
  reader = csv.DictReader(csvfile)
  for row in reader:
      print(row['UNLOCKSCREEN'])
      rows.append(row)
      
      
print(row)


rows


7
20
33
46
59
{'DATE': '10/23/2022', 'UNLOCKSCREEN': '59', 'COLDDAY': '1', 'DRUNKCOFFEE': '4', 'feature scaling UNLOCK SCREEN': '1.134615385', 'feature scaling DRUNK COFFEE': '1'}


[{'DATE': '10/19/2022',
  'UNLOCKSCREEN': '7',
  'COLDDAY': '0',
  'DRUNKCOFFEE': '0',
  'feature scaling UNLOCK SCREEN': '0.1346153846',
  'feature scaling DRUNK COFFEE': '0'},
 {'DATE': '10/20/2022',
  'UNLOCKSCREEN': '20',
  'COLDDAY': '1',
  'DRUNKCOFFEE': '1',
  'feature scaling UNLOCK SCREEN': '0.3846153846',
  'feature scaling DRUNK COFFEE': '0.25'},
 {'DATE': '10/21/2022',
  'UNLOCKSCREEN': '33',
  'COLDDAY': '1',
  'DRUNKCOFFEE': '2',
  'feature scaling UNLOCK SCREEN': '0.6346153846',
  'feature scaling DRUNK COFFEE': '0.5'},
 {'DATE': '10/22/2022',
  'UNLOCKSCREEN': '46',
  'COLDDAY': '1',
  'DRUNKCOFFEE': '3',
  'feature scaling UNLOCK SCREEN': '0.8846153846',
  'feature scaling DRUNK COFFEE': '0.75'},
 {'DATE': '10/23/2022',
  'UNLOCKSCREEN': '59',
  'COLDDAY': '1',
  'DRUNKCOFFEE': '4',
  'feature scaling UNLOCK SCREEN': '1.134615385',
  'feature scaling DRUNK COFFEE': '1'}]

In [125]:
import pandas as pd
data = pd.read_csv('Data chart template - Template.csv')
data


DATE  UNLOCKSCREEN  COLDDAY  DRUNKCOFFEE  \
0  10/19/2022             7        0            0   
1  10/20/2022            20        1            1   
2  10/21/2022            33        1            2   
3  10/22/2022            46        1            3   
4  10/23/2022            59        1            4   

   feature scaling UNLOCK SCREEN  feature scaling DRUNK COFFEE  
0                       0.134615                          0.00  
1                       0.384615                          0.25  
2                       0.634615                          0.50  
3                       0.884615                          0.75  
4                       1.134615                          1.00

In [126]:
data.columns


Index(['DATE', 'UNLOCKSCREEN', 'COLDDAY', 'DRUNKCOFFEE',
       'feature scaling UNLOCK SCREEN', 'feature scaling DRUNK COFFEE'],
      dtype='object')

In [131]:
data.UNLOCKSCREEN


AttributeError: 'numpy.ndarray' object has no attribute 'UNLOCKSCREEN'

In [168]:

from sklearn.preprocessing import MinMaxScaler
from numpy import asarray
import pandas as pd

df = pd.read_csv('Data chart template - Template.csv')

#data

data = asarray([[7, 0],
                              [20, 1],
                              [33, 2],
                              [46, 3],
                              [59, 4]])

data = (df.UNLOCKSCREEN,  df.DRUNKCOFFEE)

new = data

print(df.UNLOCKSCREEN
      )
# define min max scaler
scaler = MinMaxScaler()
# transform data
scaled = scaler.fit_transform(data)

print(scaled)


0    7
Name: UNLOCKSCREEN, dtype: int64
[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]


In [145]:
from numpy import asarray
from sklearn.preprocessing import StandardScaler

print(new)
# define standard scaler
scaler = StandardScaler()
# transform data
scaled = scaler.fit_transform(new)
print(scaled)


[[ 7  0]
 [20  1]
 [33  2]
 [46  3]
 [59  4]]
[[-1.41421356 -1.41421356]
 [-0.70710678 -0.70710678]
 [ 0.          0.        ]
 [ 0.70710678  0.70710678]
 [ 1.41421356  1.41421356]]


In [ ]:
csvfile.close()
